[project]
name = "llm-gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mibrahimbashir", email = "ibrahimbashir370@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
llm-gateway = "llm_gateway:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
